import httpx
import os
import json

VLLM_URL = os.getenv("VLLM_URL", "http://192.168.29.96:8001/v1/chat/completions")
MODEL_NAME = os.getenv("MODEL_NAME", "qwen-27b")

def generate_rag_response(query: str, context: str) -> str:
    """Synchronous generation (used by the standard /chat endpoint)."""
    system_prompt = "You are an expert AI assistant for the Yukti Platform. Use the provided context to answer the user's question."
    user_prompt = f"Context:\n{context}\n\nQuestion: {query}"

    payload = {
        "model": MODEL_NAME,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.7,
        "max_tokens": 300
    }

    try:
        response = httpx.post(VLLM_URL, json=payload, timeout=60.0)
        response.raise_for_status()
        data = response.json()
        return data["choices"][0]["message"]["content"]
    except Exception as e:
        return f"Error communicating with AI Node: {str(e)}"

async def stream_rag_response(query: str, context: str):
    """
    Asynchronous streaming generation.
    Yields tokens one by one as they are generated by the LLM.
    """
    system_prompt = "You are an expert AI assistant for the Yukti Platform. Use the provided context to answer the user's question."
    user_prompt = f"Context:\n{context}\n\nQuestion: {query}"

    payload = {
        "model": MODEL_NAME,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.7,
        "max_tokens": 300,
        "stream": True  # <-- CRITICAL: Tell vLLM to stream tokens
    }

    async with httpx.AsyncClient(timeout=60.0) as client:
        async with client.stream("POST", VLLM_URL, json=payload) as response:
            response.raise_for_status()
            async for line in response.aiter_lines():
                if line.startswith("data: "):
                    data = line[6:] # Remove "data: " prefix
                    if data.strip() == "[DONE]":
                        break
                    try:
                        chunk = json.loads(data)
                        delta = chunk["choices"][0]["delta"].get("content", "")
                        if delta:
                            yield delta
                    except json.JSONDecodeError:
                        continue
